import type { NodeConfigSchema } from '@/config/types';

// Trigger node config schemas, keyed by nodeType.
// To add a trigger: add an entry to this record — registry.ts picks it up automatically.

export const triggerConfigs: Record<string, NodeConfigSchema> = {
  'manual-trigger': {
    nodeType: 'manual-trigger',
    sections: [
      {
        title: 'Test Variables',
        fields: [
          { key: 'variables', label: 'Variables', type: 'keyvalue', description: 'Add static key-value pairs for testing', defaultValue: [] },
        ],
      },
    ],
  },

  'webhook-trigger': {
    nodeType: 'webhook-trigger',
    sections: [
      {
        title: 'Endpoint',
        fields: [
          { key: 'endpointUrl', label: 'Endpoint URL', type: 'readonly', description: 'Auto-generated HTTPS URL', defaultValue: 'https://api.workflow.app/wh/abc123' },
          { key: 'httpMethod', label: 'HTTP Method', type: 'readonly', defaultValue: 'POST' },
          { key: 'enabled', label: 'Enabled', type: 'toggle', defaultValue: true, description: 'When disabled, endpoint returns 410' },
        ],
      },
      {
        title: 'Payload Configuration',
        fields: [
          { key: 'payloadFields', label: 'Required Payload Fields', type: 'keyvalue', description: 'Define expected fields and types' },
          { key: 'contentType', label: 'Content Type', type: 'readonly', defaultValue: 'application/json' },
        ],
      },
      {
        title: 'Rate Limiting',
        fields: [
          { key: 'rateLimit', label: 'Requests per minute', type: 'number', defaultValue: 60, min: 1, max: 1000 },
        ],
      },
    ],
  },

  'form-trigger': {
    nodeType: 'form-trigger',
    sections: [
      {
        title: 'Form Definition',
        fields: [
          { key: 'formName', label: 'Form Name', type: 'text', required: true, placeholder: 'e.g., Contact Form' },
          { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional form description' },
          { key: 'publicUrl', label: 'Public URL', type: 'readonly', description: 'Auto-generated by the system after publishing' },
        ],
      },
      {
        title: 'Form Fields',
        fields: [
          {
            key: 'formFields',
            label: 'Fields',
            type: 'inputfieldlist',
            required: true,
            description: 'Fields the form will collect. At least one field is required.',
          },
        ],
      },
      {
        title: 'Access',
        fields: [
          { key: 'accessLevel', label: 'Access Level', type: 'select', required: true, options: [
            { label: 'Public', value: 'public' },
            { label: 'Tenant Users Only', value: 'tenant' },
          ], defaultValue: 'public' },
        ],
      },
    ],
  },

  'schedule-trigger': {
    nodeType: 'schedule-trigger',
    sections: [
      {
        title: 'Schedule',
        fields: [
          { key: 'scheduleType', label: 'Schedule Type', type: 'select', required: true, options: [
            { label: 'Simple Interval', value: 'interval' },
            { label: 'Specific Time', value: 'specific' },
            { label: 'Cron Expression', value: 'cron' },
          ], defaultValue: 'interval' },
          { key: 'intervalValue', label: 'Every', type: 'number', defaultValue: 30, min: 1 },
          { key: 'intervalUnit', label: 'Unit', type: 'select', options: [
            { label: 'Minutes', value: 'minutes' }, { label: 'Hours', value: 'hours' }, { label: 'Days', value: 'days' },
          ], defaultValue: 'minutes' },
          { key: 'specificTime', label: 'At Time (HH:MM)', type: 'text', placeholder: '09:00' },
          { key: 'timezone', label: 'Timezone', type: 'select', options: [
            { label: 'UTC', value: 'UTC' }, { label: 'US/Eastern', value: 'US/Eastern' },
            { label: 'US/Pacific', value: 'US/Pacific' }, { label: 'Europe/London', value: 'Europe/London' },
            { label: 'Europe/Berlin', value: 'Europe/Berlin' }, { label: 'Asia/Tokyo', value: 'Asia/Tokyo' },
          ], defaultValue: 'UTC' },
          { key: 'cronExpression', label: 'Cron Expression', type: 'text', placeholder: '0 9 * * 1-5' },
        ],
      },
    ],
  },

  'app-event-trigger': {
    nodeType: 'app-event-trigger',
    sections: [
      {
        title: 'Application & Event',
        fields: [
          { key: 'application', label: 'Application', type: 'select', required: true, options: [
            { label: 'Email', value: 'email' }, { label: 'CRM', value: 'crm' },
            { label: 'Issue Tracker', value: 'issue-tracker' }, { label: 'Database', value: 'database' },
          ]},
          { key: 'eventType', label: 'Event Type', type: 'select', required: true, options: [
            { label: 'New Email', value: 'new-email' }, { label: 'Ticket Updated', value: 'ticket-updated' },
            { label: 'New Contact', value: 'new-contact' }, { label: 'Row Inserted', value: 'row-inserted' },
          ]},
          { key: 'connection', label: 'Connection', type: 'select', options: [
            { label: 'Select connection...', value: '' },
          ]},
        ],
      },
      {
        title: 'Event Filters',
        fields: [
          { key: 'filters', label: 'Filter Conditions', type: 'keyvalue', description: 'Key-value filter pairs (e.g., folder=INBOX)' },
        ],
      },
      {
        title: 'Delivery Mode',
        fields: [
          { key: 'deliveryMode', label: 'Mode', type: 'select', options: [
            { label: 'Instant (Webhook/Push)', value: 'instant' },
            { label: 'Polling', value: 'polling' },
          ], defaultValue: 'instant' },
          { key: 'pollingInterval', label: 'Polling Interval (minutes)', type: 'number', defaultValue: 5, min: 1, max: 60 },
        ],
      },
      {
        title: 'Idempotency',
        fields: [
          { key: 'eventIdField', label: 'Event ID Field', type: 'text', placeholder: 'e.g., messageId', description: 'Field used for deduplication' },
        ],
      },
    ],
  },
};
