<?php

namespace Modules\Workflows\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Workflows\Enums\NodeConfigFieldType;
use Modules\Workflows\Models\Node;
use Modules\Workflows\Models\NodeConfigField;

class NodeDefinitionSeeder extends Seeder
{
    public function run(): void
    {
        $definitions = [
            // ── Triggers ────────────────────────────────────────────────────
            [
                'type' => 'manual-trigger',
                'label' => 'Manual',
                'category' => 'trigger',
                'description' => 'Start workflow manually',
                'color' => 'node-trigger',
                'icon' => 'MousePointerClick',
                'configFields' => [
                    ['key' => 'variables', 'label' => 'Test Variables', 'type' => 'json', 'placeholder' => '{"key": "value"}'],
                ],
            ],
            [
                'type' => 'form-trigger',
                'label' => 'Form Trigger',
                'category' => 'trigger',
                'description' => 'Start from form submission',
                'color' => 'node-trigger',
                'icon' => 'FormInput',
                'configFields' => [
                    ['key' => 'formName', 'label' => 'Form Name', 'type' => 'text', 'required' => true],
                    ['key' => 'description', 'label' => 'Description', 'type' => 'textarea'],
                    ['key' => 'publicUrl', 'label' => 'Public URL', 'type' => 'readonly', 'placeholder' => 'Auto-generated by the system'],
                    ['key' => 'formFields', 'label' => 'Form Fields', 'type' => 'json', 'required' => true, 'placeholder' => '[{"key":"name","label":"Full Name","type":"text"}]'],
                    [
                        'key' => 'accessLevel',
                        'label' => 'Access Level',
                        'type' => 'select',
                        'required' => true,
                        'options' => [
                            ['label' => 'Public', 'value' => 'public'],
                            ['label' => 'Tenant Users Only', 'value' => 'tenant'],
                        ],
                    ],
                ],
            ],

            // ── Logic ────────────────────────────────────────────────────────
            [
                'type' => 'if-node',
                'label' => 'If',
                'category' => 'logic',
                'description' => 'Conditional branching',
                'color' => 'node-logic',
                'icon' => 'GitBranch',
                'configFields' => [
                    ['key' => 'conditionExpression', 'label' => 'Condition Expression', 'type' => 'text', 'required' => true, 'placeholder' => 'context.age > 18'],
                ],
            ],
            [
                'type' => 'and-node',
                'label' => 'Fork',
                'category' => 'logic',
                'description' => 'Split execution into multiple parallel branches',
                'color' => 'node-logic',
                'icon' => 'GitFork',
                'configFields' => [
                    ['key' => 'branches', 'label' => 'Branches', 'type' => 'branches', 'required' => true],
                ],
            ],
            [
                'type' => 'merge-or',
                'label' => 'Merge Or',
                'category' => 'logic',
                'description' => 'Continue when any incoming branch completes',
                'color' => 'node-logic',
                'icon' => 'GitMerge',
                'configFields' => [],
            ],
            [
                'type' => 'merge-and',
                'label' => 'Merge And',
                'category' => 'logic',
                'description' => 'Continue when all incoming branches complete',
                'color' => 'node-logic',
                'icon' => 'Merge',
                'configFields' => [
                    ['key' => 'timeout', 'label' => 'Timeout (seconds)', 'type' => 'number', 'defaultValue' => 300],
                ],
            ],
            [
                'type' => 'switch',
                'label' => 'Switch',
                'category' => 'logic',
                'description' => 'Multi-path routing based on a value',
                'color' => 'node-logic',
                'icon' => 'Route',
                'configFields' => [
                    ['key' => 'variable', 'label' => 'Variable', 'type' => 'text', 'required' => true, 'placeholder' => 'context.status'],
                    ['key' => 'options', 'label' => 'Options', 'type' => 'tags', 'required' => true],
                ],
            ],

            // ── AI ───────────────────────────────────────────────────────────
            [
                'type' => 'ai-generator',
                'label' => 'AI Generator',
                'category' => 'ai',
                'description' => 'Generate content with AI',
                'color' => 'node-ai',
                'icon' => 'Wand2',
                'configFields' => [
                    [
                        'key' => 'contentType',
                        'label' => 'Content Type',
                        'type' => 'select',
                        'options' => [
                            ['label' => 'Email', 'value' => 'email'],
                            ['label' => 'Proposal', 'value' => 'proposal'],
                            ['label' => 'Report', 'value' => 'report'],
                            ['label' => 'Social Post', 'value' => 'social'],
                        ],
                    ],
                    ['key' => 'tone', 'label' => 'Tone', 'type' => 'text'],
                    ['key' => 'template', 'label' => 'Template / Prompt', 'type' => 'textarea', 'required' => true],
                ],
            ],

            // ── Flows ────────────────────────────────────────────────────────
            [
                'type' => 'sub-workflow',
                'label' => 'Sub Workflow',
                'category' => 'flows',
                'description' => 'Execute another workflow as a step',
                'color' => 'node-flows',
                'icon' => 'Workflow',
                'configFields' => [
                    ['key' => 'workflowId', 'label' => 'Workflow ID', 'type' => 'text', 'required' => true],
                    ['key' => 'inputMapping', 'label' => 'Input Mapping (JSON)', 'type' => 'json', 'placeholder' => '{"param":"{{variable}}"}'],
                    ['key' => 'outputVariable', 'label' => 'Output Variable', 'type' => 'text'],
                ],
            ],
            [
                'type' => 'dynamic-flow',
                'label' => 'Dynamic Flow',
                'category' => 'flows',
                'description' => 'Runtime sub-flow creation',
                'color' => 'node-flows',
                'icon' => 'Shuffle',
                'configFields' => [
                    ['key' => 'message', 'label' => 'Manager Message', 'type' => 'textarea', 'defaultValue' => 'Manager must design a custom sub-flow'],
                    ['key' => 'aiSuggestion', 'label' => 'Enable AI Suggestion', 'type' => 'toggle', 'defaultValue' => true],
                ],
            ],

            // ── Actions ──────────────────────────────────────────────────────
            [
                'type' => 'send-email',
                'label' => 'Send Email',
                'category' => 'action',
                'description' => 'Send an email via the connected Gmail workspace',
                'color' => 'node-action',
                'icon' => 'Gmail',
                'configFields' => [
                    ['key' => 'to', 'label' => 'To', 'type' => 'text', 'required' => true],
                    ['key' => 'cc', 'label' => 'CC', 'type' => 'text'],
                    ['key' => 'bcc', 'label' => 'BCC', 'type' => 'text'],
                    ['key' => 'subject', 'label' => 'Subject', 'type' => 'text', 'required' => true, 'placeholder' => 'Hello {{context.firstName}}'],
                    [
                        'key' => 'bodyType',
                        'label' => 'Body Type',
                        'type' => 'select',
                        'defaultValue' => 'text',
                        'options' => [
                            ['label' => 'Plain Text', 'value' => 'text'],
                            ['label' => 'HTML', 'value' => 'html'],
                        ],
                    ],
                    ['key' => 'body', 'label' => 'Body', 'type' => 'textarea', 'required' => true, 'placeholder' => 'Dear {{context.firstName}},'],
                ],
            ],
            [
                'type' => 'task-node',
                'label' => 'Task Node',
                'category' => 'action',
                'description' => 'Assign a task to a team member for review or approval',
                'color' => 'node-action',
                'icon' => 'UserCheck',
                'configFields' => [
                    ['key' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
                    ['key' => 'description', 'label' => 'Description', 'type' => 'textarea'],
                    ['key' => 'assignTo', 'label' => 'Assign To', 'type' => 'text', 'required' => true],
                    ['key' => 'inputFields', 'label' => 'Input Fields', 'type' => 'json', 'required' => true],
                    ['key' => 'dueWithin', 'label' => 'Due Within (hours)', 'type' => 'number', 'defaultValue' => 24],
                ],
            ],
        ];

        $allowedTypes = array_column($definitions, 'type');

        // Deactivate any nodes not in the allowed set
        Node::query()->whereNotIn('type', $allowedTypes)->update(['is_active' => false]);

        foreach ($definitions as $definition) {
            $node = Node::query()->updateOrCreate(
                ['type' => $definition['type']],
                [
                    'label' => $definition['label'],
                    'category' => $definition['category'],
                    'icon' => $definition['icon'],
                    'description' => $definition['description'],
                    'color' => $definition['color'],
                    'is_active' => true,
                ]
            );

            $keys = [];

            foreach ($definition['configFields'] as $fieldIndex => $field) {
                $keys[] = $field['key'];

                NodeConfigField::query()->updateOrCreate(
                    [
                        'node_id' => $node->id,
                        'key' => $field['key'],
                    ],
                    [
                        'label' => $field['label'],
                        'type' => NodeConfigFieldType::from($field['type'])->value,
                        'placeholder' => $field['placeholder'] ?? null,
                        'options' => $field['options'] ?? null,
                        'is_required' => $field['required'] ?? false,
                        'default_value' => array_key_exists('defaultValue', $field) ? $field['defaultValue'] : null,
                        'sort_order' => $fieldIndex + 1,
                    ]
                );
            }

            NodeConfigField::query()
                ->where('node_id', $node->id)
                ->whereNotIn('key', $keys)
                ->delete();
        }
    }
}
